// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCG.Infrastructure;

#nullable disable

namespace TCG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531212631_DBUpdate")]
    partial class DBUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TCG.Domain.Entities.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueId"));

                    b.Property<string>("LeagueDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_description");

                    b.Property<string>("LeagueGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_game");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_name");

                    b.HasKey("LeagueId");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Pairing", b =>
                {
                    b.Property<int>("PairingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pairing_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairingId"));

                    b.Property<int>("Player1Id")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_1");

                    b.Property<int?>("Player1Score")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_1_score");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_2");

                    b.Property<int?>("Player2Score")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_2_score");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_winner");

                    b.HasKey("PairingId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("pairings", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_email");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_first_name");

                    b.Property<string>("StaffMobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_mobile");

                    b.Property<string>("StaffPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_password");

                    b.Property<bool>("StaffRoleHead")
                        .HasColumnType("boolean")
                        .HasColumnName("staff_role_head");

                    b.Property<bool>("StaffRoleManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("staff_role_management");

                    b.Property<string>("StaffSurname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_surname");

                    b.HasKey("StaffId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_league");

                    b.Property<DateOnly>("TournamentDate")
                        .HasColumnType("date")
                        .HasColumnName("tournament_date");

                    b.Property<string>("TournamentDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_description");

                    b.Property<decimal>("TournamentEntryFee")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tournament_entry_fee");

                    b.Property<string>("TournamentFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_format");

                    b.Property<string>("TournamentGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_game");

                    b.Property<int>("TournamentMaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_max_participants");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.Property<string>("TournamentPairing")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_pairing");

                    b.Property<bool>("TournamentRequireDeck")
                        .HasColumnType("boolean")
                        .HasColumnName("tournament_require_deck");

                    b.Property<int?>("TournamentRoundNum")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_round_num");

                    b.Property<TimeOnly>("TournamentTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tournament_time");

                    b.HasKey("TournamentId");

                    b.HasIndex("LeagueId");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.TournamentPlayer", b =>
                {
                    b.Property<int>("TournamentPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentPlayerId"));

                    b.Property<string>("PlayerName")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_name");

                    b.Property<string>("PlayerSwissMatchPoints")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_swiss_match_points");

                    b.Property<string>("PlayerSwissPoints")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_swiss_points");

                    b.Property<string>("PlayerSwissScore")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_swiss_score");

                    b.Property<string>("PlayerSwissWins")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_swiss_wins");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tp_tournament");

                    b.HasKey("TournamentPlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournament_players", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Pairing", b =>
                {
                    b.HasOne("TCG.Domain.Entities.TournamentPlayer", "Player1")
                        .WithMany("PairingsAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCG.Domain.Entities.TournamentPlayer", "Player2")
                        .WithMany("PairingsAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TCG.Domain.Entities.TournamentPlayer", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("TCG.Domain.Entities.League", "League")
                        .WithMany("Tournaments")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");
                });

            modelBuilder.Entity("TCG.Domain.Entities.TournamentPlayer", b =>
                {
                    b.HasOne("TCG.Domain.Entities.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TCG.Domain.Entities.League", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("TCG.Domain.Entities.TournamentPlayer", b =>
                {
                    b.Navigation("PairingsAsPlayer1");

                    b.Navigation("PairingsAsPlayer2");
                });
#pragma warning restore 612, 618
        }
    }
}
