// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCG.Infrastructure;

#nullable disable

namespace TCG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309210749_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TCG.Domain.Entities.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueId"));

                    b.Property<string>("LeagueDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_description");

                    b.Property<string>("LeagueGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_game");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("league_name");

                    b.HasKey("LeagueId");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<int>("MatchRoundNum")
                        .HasColumnType("integer")
                        .HasColumnName("match_round_num");

                    b.Property<int>("PairingId")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_id");

                    b.Property<bool>("Player1Winner")
                        .HasColumnType("boolean")
                        .HasColumnName("player_1_winner");

                    b.Property<bool>("Player2Winner")
                        .HasColumnType("boolean")
                        .HasColumnName("player_2_winner");

                    b.HasKey("MatchId");

                    b.HasIndex("PairingId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Pairing", b =>
                {
                    b.Property<int>("PairingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pairing_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairingId"));

                    b.Property<int>("PairingTp1")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_1");

                    b.Property<int>("PairingTp2")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_tp_2");

                    b.Property<string>("PairingWinner")
                        .HasColumnType("text")
                        .HasColumnName("pairing_winner");

                    b.HasKey("PairingId");

                    b.HasIndex("PairingTp1");

                    b.HasIndex("PairingTp2");

                    b.ToTable("pairings", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_email");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_first_name");

                    b.Property<string>("StaffMobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_mobile");

                    b.Property<string>("StaffPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_password");

                    b.Property<bool>("StaffRoleHead")
                        .HasColumnType("boolean")
                        .HasColumnName("staff_role_head");

                    b.Property<bool>("StaffRoleManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("staff_role_management");

                    b.Property<string>("StaffSurname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staff_surname");

                    b.HasKey("StaffId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<DateOnly>("TournamentDate")
                        .HasColumnType("date")
                        .HasColumnName("tournament_date");

                    b.Property<string>("TournamentDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_description");

                    b.Property<decimal>("TournamentEntryFee")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tournament_entry_fee");

                    b.Property<string>("TournamentFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_format");

                    b.Property<string>("TournamentGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_game");

                    b.Property<int?>("TournamentLeague")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_league");

                    b.Property<int>("TournamentMaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_max_participants");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.Property<string>("TournamentPairing")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_pairing");

                    b.Property<bool>("TournamentRequireDeck")
                        .HasColumnType("boolean")
                        .HasColumnName("tournament_require_deck");

                    b.Property<int?>("TournamentRoundNum")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_round_num");

                    b.Property<TimeOnly>("TournamentTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tournament_time");

                    b.HasKey("TournamentId");

                    b.HasIndex("TournamentLeague");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.TournamentPlayer", b =>
                {
                    b.Property<int>("TpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TpId"));

                    b.Property<string>("TpPlayerName")
                        .HasColumnType("text")
                        .HasColumnName("tp_player_name");

                    b.Property<int>("TpTournament")
                        .HasColumnType("integer")
                        .HasColumnName("tp_tournament");

                    b.HasKey("TpId");

                    b.HasIndex("TpTournament");

                    b.ToTable("tournament_players", (string)null);
                });

            modelBuilder.Entity("TCG.Domain.Entities.Match", b =>
                {
                    b.HasOne("TCG.Domain.Entities.Pairing", null)
                        .WithMany()
                        .HasForeignKey("PairingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TCG.Domain.Entities.Pairing", b =>
                {
                    b.HasOne("TCG.Domain.Entities.TournamentPlayer", null)
                        .WithMany()
                        .HasForeignKey("PairingTp1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCG.Domain.Entities.TournamentPlayer", null)
                        .WithMany()
                        .HasForeignKey("PairingTp2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("TCG.Domain.Entities.League", null)
                        .WithMany()
                        .HasForeignKey("TournamentLeague")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TCG.Domain.Entities.TournamentPlayer", b =>
                {
                    b.HasOne("TCG.Domain.Entities.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TpTournament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TCG.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("TournamentPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
