<!-- References:
[1]: Microsoft (2026) aspnetcore (Version 10.0.2). [Source Code] Available from: https://github.com/dotnet/aspnetcore [Accessed 30/01/2026].
-->

<!-- <-*****Microsoft (2026) [1] - START -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<AssemblyName>TCG.Application</AssemblyName>
	<RootNamespace>TCG.Application</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Analyzers" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TCG.Domain\TCG.Domain.csproj" />
  </ItemGroup>

</Project>
<!-- <-*****Microsoft (2026) [1] - END -->
