<!-- References:
[1]: Microsoft (2026) aspnetcore (Version 10.0.2). [Source Code] Available from: https://github.com/dotnet/aspnetcore [Accessed 30/01/2026].
-->

<!-- <-*****Microsoft (2026) [1] - START -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>TCG.Application</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TCG.Domain\TCG.Domain.csproj" />
  </ItemGroup>

</Project>
<!-- <-*****Microsoft (2026) [1] - END -->