<!-- References:
[1]: Microsoft (2026) aspnetcore (Version 10.0.2). [Source Code] Available from: https://github.com/dotnet/aspnetcore [Accessed 30/01/2026].
[2]: Microsoft (2026) Microsoft.EntityFrameworkCore (Version 10.0.2). [Source Code] Available from: https://www.nuget.org/packages/microsoft.entityframeworkcore [Accessed 30/01/2026].
-->

<!-- <-*****Microsoft (2026) [1] - START -->
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<AssemblyName>TCG.Website</AssemblyName>
		<RootNamespace>TCG.Website</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
		<UserSecretsId>bab33b6f-305b-412e-8e9b-41f5232fea2b</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>

		<!-- <-*****Microsoft (2026) [1] - END -->

		<!-- <-*****Microsoft (2026) [2] - START -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<!-- <-*****Microsoft (2026) [2] - END -->
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TCG.Infrastructure\TCG.Infrastructure.csproj" />
	  <ProjectReference Include="..\TCG.Application\TCG.Application.csproj" />
	</ItemGroup>

</Project>
